apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: redis-operator

commonLabels:
  app.kubernetes.io/name: redis-operator
  app.kubernetes.io/instance: redis-operator

components:
  - ../../components/resources/
  - ../../components/version/

resources:
  - ../minimal/
